#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           7
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# rules for applications' default desktops
bspc config ignore_ewmh_focus true
bspc rule -a obsidian desktop=9 follow=off focus=off
bspc rule -a easyeffects desktop=0 follow=off focus=off
bspc rule -a pavucontrol desktop=0 follow=off focus=off
bspc rule -a Blueberry.py desktop=0 follow=off focus=off
